import React from 'react'
import '../App.css'

export default function About() {
  return (
    <div className='container my-5 about'>
      <div>
        <strong><h1>About Us</h1></strong>
        <br/>
        <p className='about-p'>
        Using our password pattern generator, you can create a password that is unique to you.
        It will be easier for you to remember the password if you use this method.
        There is no need to remember long and complex passwords generated by the system; all you need to know is your pattern and then you will get your password.
        </p>
      </div>
      <br/>
      <div className='about-div'>
        <strong><h1>Why should my password be random?</h1></strong>
        <br/>
        <p className='about-p'>
        Random passwords are hard to guess and harder for computer programs to crack. 
        If there's a discernible pattern, the odds of an attacker using a brute force attack and gaining 
        access to your account goes up exponentially. 
        Random passwords might contain a jumble of unrelated characters, but combining unrelated words 
        also works. 
        That's how the 1Password Strong Password Generator creates passwords that are easy to remember 
        but still cryptographically strong.
        </p>
      </div>
    </div>
  )
}
